lang: fr

project:
  output-dir: build/fr
  render:
    - "courses/**/fr/**/*.qmd"
    - "!courses/**/fr/slides/**/*.qmd"

crossref:
  fig-prefix: Figure
  tbl-prefix: Tableau
  eq-prefix: Équation

format:
  html:
    lang: fr
  pdf:
    lang: fr
