project:
  type: default
  output-dir: build
  execute-dir: project

execute:
  freeze: auto
  daemon: false
  cache: false

crossref:
  chapters: true
  fig-prefix: Figure
  tbl-prefix: Table
  eq-prefix: Equation

format:
  html:
    embed-resources: true
    html-math-method: mathml
    toc: true
    link-external-newwindow: false
  pdf:
    pdf-engine: xelatex
    latex-auto-install: false
    keep-tex: true
    documentclass: scrreprt
    geometry:
      - margin=22mm
    include-in-header:
      text: |
        \usepackage{fontspec}
        \usepackage{unicode-math}
        \widowpenalty=10000
        \clubpenalty=10000
